"""Add task_name and task_no to submissions

Revision ID: 786378e6e511
Revises: 398274d89756
Create Date: 2025-06-12 00:37:23.509418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786378e6e511'
down_revision: Union[str, None] = '398274d89756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('task_name', sa.String(), nullable=False))
    op.add_column('submissions', sa.Column('task_no', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'task_no')
    op.drop_column('submissions', 'task_name')
    # ### end Alembic commands ###
